# Generated by Django 3.2.12 on 2024-04-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('was_blocked', models.BooleanField(default=False)),
                ('block_user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Friend_Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_canceled', models.BooleanField(default=False)),
                ('was_refused', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user1_id', models.IntegerField()),
                ('user2_id', models.IntegerField()),
                ('tournament_id', models.IntegerField(null=True)),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_canceled', models.BooleanField(default=False)),
                ('was_refused', models.BooleanField(default=False)),
                ('has_finished', models.BooleanField(default=False)),
                ('user1_score', models.IntegerField(default=0)),
                ('user2_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_room_id', models.IntegerField()),
                ('sender_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('creator_id', models.IntegerField()),
                ('has_started', models.BooleanField(default=False)),
                ('has_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments_Users',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('was_accepted', models.BooleanField(default=False)),
                ('was_canceled', models.BooleanField(default=False)),
                ('was_refused', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=100)),
                ('avatar', models.BinaryField(null=True)),
                ('num_games_won', models.IntegerField(default=0)),
                ('num_tournaments', models.IntegerField(default=0)),
                ('num_tournaments_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
